### ISSUE TITLE
Clean up code

### ISSUE THREAD

**Issue by Xarlos89** [Xarlos89/ZorakBot#10]

**Comment by Xarlos89** [comment]
Goal is to have as little code in Main.py as possible. We do great with our 'Fun_funcs', but out Utility funcs are all over. Would love to move some of that bulk into the utility_funcs.py file.

**Comment by SilverscaleClockwork** [comment]
@Xarlos89 
Would a folder with seperated files for `fun`, `utility` and `admin` classes be more of use?
This would mean one the functions would be decently ordered. (1 function per command, a class + setup function per file) 
The group command would have groups and you have less of a mess to struggle with.
