### ISSUE TITLE
Cog Refactor

### ISSUE THREAD

**Issue by Xarlos89** [Xarlos89/ZorakBot#67]
Cogs need to be cleaned up and larger cogs need to be split into smaller parts

**Comment by richardphi1618** [comment]
I think this will go hand in hand with the slash groups I would like to implement

**Comment by Xarlos89** [comment]
100% will. 
The idea behind this one was to pull out huge cogs like the "fun" cog and split it into more manageable, specific cogs. 
Also, cogs should not do things that are outside of their scope. Def looking forward tot his one though.
